version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: numpy
    versions:
    - ">= 1.20.a, < 1.21"
  - dependency-name: youtube-dl
    versions:
    - 2021.3.31
    - 2021.4.1
